name: Main
on:
  push:
    branches:
      - main

  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test

      - uses: actions/checkout@v1

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: bubkoo/release-github-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false


  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   
          fetch-depth: 0               

      - name: Git Version
        uses: codacy/git-version@2.5.4

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "devopsleony"
          heroku_email: "leonyra@hotmail.com"